# docker-compose.yml
version: '3'

services:
  nginx:
    image: 'nginx:latest'
    networks:
    - net99
    volumes:
    - .:/usr/share/nginx/html
    ports:
     - "80:80"
  node:
    image: 'spe/node_canvas:latest'
    networks:
    - net99
    ports:
     - "8080:8080"
    volumes:
    - .:/root
networks:
  net99:
    driver: bridge
